OpenShift Pipelines is provided as an OpenShift add-on that can be installed via an operator that is available in the OpenShift OperatorHub.

Operators may be installed into a single namespace and only monitor resources in that namespace, but the OpenShift Pipelines Operator installs globally on the cluster and monitors and manage pipelines for every single user in the cluster.

To install the operator globally, you need to be a cluster administrator user. In this workshop environment, the operator has already been installed for you

== Verify installation

The OpenShift Pipelines Operator provides all its resources under a single API group: tekton.dev. You can see the new resources by running: 

[source,bash,role=execute-1]
----
oc api-resources --api-group=tekton.dev
----

=== Verify user roles

To validate that your user has the appropriate roles, you can use the `oc auth can-i` command to see whether you can create Kubernetes custom resources of the kind needed by the OpenShift Pipelines Operator.

The custom resource you need to create an OpenShift Pipelines pipeline is a resource of the kind pipeline.tekton.dev in the tekton.dev API group. To check that you can create this, run:

[source,bash,role=execute-1]
----
oc auth can-i create pipeline.tekton.dev
----

Or you can use the simplified version:

[source,bash,role=execute-1]
----
oc auth can-i create Pipeline
----

When run, if the response is yes, you have the appropriate access.

Verify that you can create the rest of the Tekton custom resources needed for this workshop by running the commands below. All of the commands should respond with yes.

[source,bash,role=execute-1]
----
oc auth can-i create Task
----

[source,bash,role=execute-1]
----
oc auth can-i create PipelineResource
----

[source,bash,role=execute-1]
----
oc auth can-i create PipelineRun
----

Now that we have verified that you can create the required resources let's start the workshop.
