For this tutorial, you're going to create a simple application that involves a https://github.com/openshift-pipelines/vote-ui[frontend] and https://github.com/openshift-pipelines/vote-api[backend]. This application needs to deploy in a new project (i.e. Kubernetes namespace). You can start by creating the project with:

[source,bash,role=execute-1]
----
oc project pipelines-tutorial
----

You can also deploy the same applications by applying the artifacts available in k8s directory of the respective repo.

== Tasks

A **Task** defines a series of `steps` that run in a desired order and complete a set amount of build work. Every `Task` runs as a Pod on your Kubernetes cluster with each `step` as its own container. For example, the following `Task` outputs "Hello World":

[source,yaml,role=copypaste]
----
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello
spec:
  steps:
    - name: say-hello
      image: registry.access.redhat.com/ubi8/ubi
      command:
        - /bin/bash
      args: ['-c', 'echo Hello World']
----

Apply this Task to your cluster just like any other Kubernetes object. Then run it using `tkn`, the CLI tool for Tekton.

[source,bash,role=execute-1]
----
oc apply -f tasks/hello.yaml
----

[source,bash,role=execute-1]
----
tkn task start --showlog hello
----

The output will look similar to the following:

[source,bash]
----
TaskRun started: hello-run-9cp8x
Waiting for logs to be available...
[say-hello] Hello World
----

In the next section, you will examine the task definitions that will be needed for our pipeline.