The OpenShift Pipelines Operator is installed to monitor requests to create pipelines and related resources.
The operator can only be deployed and setup by a cluster admin of the OpenShift cluster,
as we have previously discussed.

The OpenShift Pipelines Operator has been pre-installed on the OpenShift cluster for
this workshop and is ready for use. Your user has been granted the appropriate permissions
to create `Pipelines`, `Tasks`, `PipelineRuns`, and `TaskRuns` for this workshop.

The OpenShift Pipelines Operator provides all its resources under a single API group: `tekton.dev`.
To see all the resources provided by the operator, run the following command:

[source,bash,role=execute]
----
oc api-resources --api-group=tekton.dev
----

Did you type the command in yourself? If you did, click on the command instead and
you will find that it is executed for you. You can click on any command which has the +++<span class="fas fa-play-circle"></span>+++ icon
shown to the right of it, and it will be copied to the interactive terminal and run.

To validate that your user has been granted the appropriate roles, you can use the `oc auth can-i`
command to see whether you can create Kubernetes custom resources of the kind the OpenShift Pipelines Operator
responds to.

The custom resource you need to create an OpenShift Pipelines pipeline is a resource of the
kind `pipeline.tekton.dev` in the `tekton.dev` API group. To check that you can create this, run:

[source,bash,role=execute]
----
oc auth can-i create pipeline.tekton.dev
----

Or you can use the simplified version:

[source,bash,role=execute]
----
oc auth can-i create Pipeline
----

When run, if the response is `yes`, you have the appropriate access.

Verify that you can create the rest of the Tekton custom resources needed for this
workshop by running the commands below. All of the commands should respond with `yes`.

Verify you can create a Tekton `Task`:

[source,bash,role=execute]
----
oc auth can-i create Task
----

Verify you can create a Tekton `PipelineResource`:

[source,bash,role=execute]
----
oc auth can-i create PipelineResource
----

Verify you can create a Tekton `PipelineRun`:

[source,bash,role=execute]
----
oc auth can-i create PipelineRun
----

Now that we have verified that you can create the required resources, let's start the
workshop. Clear your terminal before continuing:

[source,bash,role=execute-1]
----
clear
----
