WORKSHOP_NAME=lab-tekton-pipelines
WORKSHOP_IMAGE=quay.io/openshiftlabs/lab-tekton-pipelines:4.6
WORKSHOP_TITLE="OpenShift Pipelines with Tekton"
WORKSHOP_DESCRIPTION="Developing applications using OpenShift pipelines"
CONSOLE_IMAGE=quay.io/openshift/origin-console:4.6
SPAWNER_PASSWORD=openshift
RESOURCE_BUDGET=custom
MAX_SESSION_AGE=7200
IDLE_TIMEOUT=300
SERVER_LIMIT=50
