A pipeline defines a number of tasks that should be executed and how they interact
with each other via their inputs and outputs.

In this tutorial, you will create a pipeline that takes the source code of a Node.js
application from GitHub and then builds and deploys it on OpenShift using S2I and Buildah.

Below is a YAML file that represents the above pipeline:

[source,yaml]
----
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: deploy-pipeline
spec:
  resources:
  - name: app-git
    type: git
  - name: app-image
    type: image
  tasks:
  - name: build
    taskRef:
      name: s2i-nodejs
    params:
      - name: TLSVERIFY
        value: "false"
    resources:
      inputs:
      - name: source
        resource: app-git
      outputs:
      - name: image
        resource: app-image
  - name: deploy
    taskRef:
      name: openshift-client
    runAfter:
      - build
    params:
    - name: ARGS
      value: "rollout latest nodejs-ex"
----

This pipeline performs the following:

1. Clones the source code of the application from a git repository (i.e., `app-git` resource)
2. Builds the container image using the `s2i-nodejs` task that generates a Dockerfile for the application and uses Buildah to build the image
3. The application image is pushed to an image registry (i.e., `app-image` resource)
4. The new application image is deployed on OpenShift using the `openshift-cli` task

The pipeline definition above shows how tasks can be added to a pipeline.
Each pipeline has a `tasks` property. Under this property, each `task` has a `name`.
For this pipeline, it has two tasks named `build` and `deploy`. The `taskRef` property under each
task `name` is where the tasks you just created can be specified as part of the pipeline.

You might have noticed that there are no references to the nodejs-ex git repository
and its image in the registry. That's because pipelines in Tekton are designed to
be generic and reusable across environments and stages through the application's lifecycle.

Pipelines abstract away the specifics of the git source repository and image to be
produced as pipeline resources. When triggering a pipeline, you can provide different
git repositories and image registries to be used during a pipeline execution. You
will do that in the next section.

For the `deploy` task of the pipeline, you can see under the `params` property that
a value is passed: `"rollout latest nodejs-ex"`. This argument is how `oc rollout latest nodejs-ex`
will be run for the `oc` step of the `openshift-client` `task`. This command deploys
an image called nodejs-ex that has the tag `latest` associated with it, meaning the
most recently pushed version of the image.

The execution order of tasks is determined based on the dependencies that are
defined between the tasks via `inputs` and `outputs` as well as explicit orders
that are defined via `runAfter`. You'll notice the `deploy` task above has a `runAfter`
property specifying to only execute after the `build` task is complete.

Create the Pipeline
-------------------

The command below uses `oc` to take the pipeline definition from above from a
local directory and then creates it in your OpenShift project. Run the command below to
create the pipeline:

[source,bash,role=execute-1]
----
oc create -f exercise/deploy-pipeline.yaml
----

You can see the pipeline you have created using `tkn`:

[source,bash,role=execute-1]
----
tkn pipeline ls
----

In the next section, you will focus on creating Tekton pipeline resources.
Clear your terminal before continuing:

[source,bash,role=execute-1]
----
clear
----
