**Task**'s consist of a number of steps that are executed sequentially. Each **task** is executed in a separate container within the same pod. They can also have inputs and outputs in order to interact with other tasks in the pipeline.

Here is an example of a Maven task for building a Maven-based Java application:

[source,yaml]
----
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: maven-build
spec:
  inputs:
    resources:
    - name: workspace-git
      targetPath: /
      type: git
  steps:
  - name: build
    image: maven:3.6.0-jdk-8-slim
    command:
    - /usr/bin/mvn
    args:
    - install
----

When a **task** starts running, it starts a pod and runs each **step** sequentially in a separate container on the same pod. This task happens to have a single step, but tasks can have multiple steps, and, since they run within the same pod, they have access to the same volumes in order to cache files, access configmaps, secrets, etc. `Task`s can also receive inputs (e.g. a git repository) and outputs (e.g. an image in a registry) in order to interact with each other.

Note that only the requirement for a git repository is declared on the task and not a specific git repository to be used. That allows `task`s to be reusable for multiple pipelines and purposes. You can find more examples of reusable `task`s in the link:https://github.com/tektoncd/catalog[Tekton Catalog] and link:https://github.com/openshift/pipelines-catalog[OpenShift Catalog] repositories.

Install the `openshift-client` and `s2i-java` tasks from the catalog repository using `oc` or `kubectl`, which you will need for creating a pipeline in the next section:

[source,bash,role=execute-1]
----
oc create -f tektontasks/openshift-client-task.yaml
oc create -f tektontasks/s2i-java-8-task.yaml
----

NOTE: For convenience, the tasks have been copied from it's original location in the link:https://github.com/tektoncd/catalog[Tekton Catalog] to the workshop.

You can take a look at the list of install `task`s using the [Tekton CLI](https://github.com/tektoncd/cli/releases) already installed on the workshop environment:

[source,bash,role=execute-1]
----
tkn task ls
----

You should see similar output to this:

[source,bash]
----
NAME               AGE
openshift-client   58 seconds ago
s2i-java-8         1 minute ago
----