Now that you have created `tasks`, a `pipeline`, and `pipelineresources`,
you are ready to trigger a `pipeline` that will deploy the nodejs-ex application
out to OpenShift.

As mentioned earlier, a `pipelinerun` is the custom resource used to trigger a
`pipeline`. In this exercise, you will create a `pipelinerun` via `tkn` to deploy
the nodejs-ex application out to OpenShift.

The `pipelinerun` definition below is how you can trigger the `pipeline` and tie
it to the git and image resources that are used for this specific invocation:

[source,yaml]
----
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: deploy-pipelinerun-
spec:
  pipelineRef:
    name: deploy-pipeline
  trigger:
    type: manual
  serviceAccount: 'pipeline'
  resources:
  - name: app-git
    resourceRef:
      name: nodejs-ex-git
  - name: app-image
    resourceRef:
      name: nodejs-ex-image
----

Under the spec property, you'll see the pipelineRef property where the `pipeline`
to be used is specified. You should see the name of the `pipeline` you created (i.e., deploy-pipeline).

Since this `pipelinerun` will be triggered manually by you using `tkn`, the trigger
property is set to manual. The trigger property is used to specify when the `pipeline`
should execute. This property is how a webhook can be used to trigger a `pipelinerun`
via a code commit to a git repository instead of triggering manually.

The last property of the `pipelinerun` of note is resources. This is how the specific
git repository and image registry urls can be entered for the `pipelinerun`. You'll
see the `pipelineresource` references you just created in the `pipelinerun` definition.

While learning about the resource definition behind a `pipelinerun` is important,
you do not have to define this resource yourself to trigger a `pipelinerun`. You
can create the above `pipelinerun` to deploy the nodejs-ex application out to OpenShift via `tkn`.

The `tkn` command below triggers a `pipelinerun`. The `-r` flag allows you specify
what `pipelineresources` will be included in a `pipelinerun`. You can see the git and image
`pipelineresources` you created earlier.

You will also notice the `-s` flag for specifying a service account. This is how you
can add your pipeline service account to the `pipelinerun`.

Run the command below to kick off the `pipelinerun`:

[source,bash,role=execute-1]
----
tkn pipeline start deploy-pipeline \
        -r app-git=nodejs-ex-git \
        -r app-image=nodejs-ex-image \
        -s pipeline
----

After running the command above, the `pipeline` you created earlier is now
instantiated and a number of pods are created to execute the `tasks` that are
defined as part of the `pipeline`. After 4-5 minutes, the `pipelinerun` should
finish successfully.

To view the `pipelinerun` created, run the following `tkn` command:

[source,bash,role=execute-1]
----
tkn pr ls
----

Tekton CLI Logs
---------------

To view the logs for the `pipelinerun` you need the unique name assigned to it
when you ran `tkn pipeline start`. This is the same name as `tkn pr ls` outputs
and actually corresponds to the name of the pod for the `pipelinerun`.

To grab the name of this into an environment variable, run:

[source,bash,role=execute-1]
----
POD=`tkn pr ls -o jsonpath='{$.items[?(@.status.conditions[0].reason=="Running")].metadata.name}' | tr ' ' '\n' | head -1`; echo $POD
----

Then run:

[source,bash,role=execute-1]
----
tkn pr logs $POD -f
----

The logs output tells you what `tasks` are running as well as what step it is running.
You'll see the output structured as `[task_name : step_name]`. An example from this
`pipelinerun` is below for the generate step of the build `task`:

[source,bash]
----
[build : generate]
----

As these logs come in via `tkn`, you can see output from the task-step combinations from the build `task`:

[source,bash]
----
[build : generate]
[build : build]
[build : push]
----

You can also eventually see the output of the deploy `task` execution with its one step:

[source,bash]
----
[deploy : oc]
----

Upon the successful completion of the `pipelinerun`, you will see the following output from the logs:

[source,bash]
----
[deploy : oc] deploymentconfig.apps.openshift.io/nodejs-ex rolled out
----

While the `pipelinerun` is executing, you can take a look at how you can visualize
a `pipelinerun` through the OpenShift web console in the next section. Leave the logs
running so that you can confirm the successful deployment message when the `pipelinerun` finishes.
