Now that the `pipeline` is created, you can trigger it to execute the tasks specified in the `pipeline`. Triggering `pipelines` is an area that is under development and in the next release it will be possible to be done via the OpenShift web console and Tekton CLI. In this tutorial, you will trigger the pipeline through creating the Kubernetes objects (the hard way!) in order to learn the mechanics of triggering.

First, you should create `pipelineresources` that contain the specifics of the Git repository and image registry to be used in the `pipeline` during execution. Expectedly, these are also reusable across multiple pipelines.

The following `pipelineresource` defines the Git repository and reference for the PetClinic application:

[source,yaml]
----
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: petclinic-git
spec:
  type: git
  params:
  - name: url
    value: https://github.com/spring-projects/spring-petclinic
----

And the following defines the OpenShift internal registry for the PetClinic image to be pushed to:

[source,yaml]
----
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: petclinic-image
spec:
  type: image
  params:
  - name: url
    value: image-registry.openshift-image-registry.svc:5000/pipelines-tutorial/spring-petclinic
----

Create the above pipeline resources via the OpenShift web console using the same steps used earlier for creating the `pipeline` or execute the following `oc` commands:

[source,bash,role=execute-1]
----
oc create -f ./code/exercise/petclinic-git-pipeline-resource.yaml
oc create -f ./code/exercise/petclinic-image-pipeline-resource.yaml
----

A `pipelinerun` is how you can trigger a `pipeline` and tie it to the Git and image resources that should be used for this specific invocation:

[source,yaml]
----
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: petclinic-deploy-pipelinerun-
spec:
  pipelineRef:
    name: deploy-pipeline
  trigger:
    type: manual
  serviceAccount: 'pipeline'
  resources:
  - name: app-git
    resourceRef:
      name: petclinic-git
  - name: app-image
    resourceRef:
      name: petclinic-image
----

Create the above `pipelinerun` via the OpenShift web console using the same steps used earlier for creating the `pipeline` or run the following `oc` command:

[source,bash,role=execute-1]
----
oc create -f ./code/exercise/petclinic-deploy-pipelinerun.yaml
----

The `pipeline` you created earlier is now instantiated and creating a number of pods to execute the `tasks` that are defined in the `pipeline`. After a few minutes, the `pipeline` should finish successfully.

[source,bash,role=execute-1]
----
# tkn pr ls
NAME                                 STARTED         DURATION    STATUS
petclinic-deploy-pipelinerun-lkq7d   7 minutes ago   3 minutes   Succeeded
----

= TODO: Show how to view pipelinerun through web console

Check the `pipelinerun` logs as it executes:

[source,bash,role=execute-1]
----
$ tkn pr logs petclinic-deploy-pipelinerun-lkq7d -f
...

[s2i-java-8 : nop] Build successful

[openshift-client : oc] deploymentconfig.apps.openshift.io/spring-petclinic rolled out

[openshift-client : nop] Build successful
----

Looking back at the project, you should see that the PetClinic image is successfully built and deployed.

images:images/petclinic-deployed-2.png[PetClinic Deployed]
